using System;
using System.Data;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



namespace PRG3204_Group06_Assignment_Chinese_Cultural_Society
{
      public partial class serviceSupport : System.Web.UI.Page
      {
        SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["databaseConstr"].ConnectionString);
        protected void Page_PreRender(object sender, EventArgs e)
        {
            lblHeader.Text = "SERVICE & SUPPORT";
            btnFAQ.Text = "FAQ";
            btnFeedback.Text = "Feedback Form";

            string userType = "";

            if (Session["userType"] != null)
                userType = Session["userType"].ToString();

            if (userType == "AD")
            {
                btnInsertFAQ.Text = "+ Add FAQs";
                btnPassRecover.Visible = false;
            }
            else if(userType == "ME")
            {
                btnInsertFAQ.Visible = false;
                btnPassRecover.Visible = false;
            }
            else
            {
                btnPassRecover.Text = "Password Recovery";
                btnPassRecover.Visible = true;
            }
        }

        protected void Page_Load(object sender, EventArgs e)
        {
            string userType = "";

            if (Session["userType"] != null)
                userType = Session["userType"].ToString();

            if (userType == "AD")
            {
                mvUserType.ActiveViewIndex = 0;
                mvUserTypeFeed.ActiveViewIndex = 0;
                GridViewFAQ.AutoGenerateEditButton = true;
                GridViewFAQ.AutoGenerateDeleteButton = true;
            }
            else
            {
                mvUserType.ActiveViewIndex = 1;
                mvUserTypeFeed.ActiveViewIndex = 1;
                GridViewFAQ.AutoGenerateEditButton = false;
                GridViewFAQ.AutoGenerateDeleteButton = false;
            }

            if(!IsPostBack)
                mvSerSupSelect.ActiveViewIndex = 0;
        }

        protected void btnFAQ_Click(object sender, EventArgs e)
        {
            mvSerSupSelect.ActiveViewIndex = 0;
            btnFAQ.BackColor = System.Drawing.Color.FromArgb(173, 222, 252);
            btnFAQ.ForeColor = System.Drawing.Color.White;
            btnFeedback.BackColor = System.Drawing.Color.White;
            btnFeedback.ForeColor = System.Drawing.Color.Black;
        }

        protected void btnFeedback_Click(object sender, EventArgs e)
        {
            mvSerSupSelect.ActiveViewIndex = 1;
            btnFeedback.BackColor = System.Drawing.Color.FromArgb(173, 222, 252);
            btnFeedback.ForeColor = System.Drawing.Color.White;
            btnFAQ.BackColor = System.Drawing.Color.White;
            btnFAQ.ForeColor = System.Drawing.Color.Black;
        }

        protected void btnInsertFAQ_Click(object sender, EventArgs e)
        {
            Response.Redirect("addFAQ.aspx");
        }

        protected void btnAddFeedQues_Click(object sender, EventArgs e)
        {
            Response.Redirect("addFeedbackQuestion.aspx");
        }

        protected void btnSubmitFeedBack_Click(object sender, EventArgs e)
        {
            try
            {
                conn.Open();

                SqlCommand cmd = new SqlCommand("INSERT INTO feedbackFromUser(feedBackResponse,feedbackFormQuesID)values (@feedbackDesc, 1)", conn);

                cmd.Parameters.AddWithValue("@feedbackDesc", txtFeedBackUser.Text);

                cmd.ExecuteNonQuery(); //inserting

                conn.Close();

                lblFeedbackToFeedback.Text = "Thank you very much ~ Your feedback will be appreciated.";
            }
            catch (Exception ex)
            {

            }

            txtFeedBackUser.Text = "";
        }

        protected void btnViewRes_Click(object sender, EventArgs e)
        {
            Response.Redirect("viewResponse.aspx");
        }

        protected void btnPassRecover_Click(object sender, EventArgs e)
        {
            Response.Redirect("passwordRecovery.aspx");
            Session["pageNo"] = 0;
        }
    }
}