<%@ Page Title="" Language="C#" MasterPageFile="~/navMenu.Master" AutoEventWireup="true" CodeBehind="serviceSupport.aspx.cs" Inherits="PRG3204_Group06_Assignment_Chinese_Cultural_Society.serviceSupport" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="serSupCSS.css" rel="stylesheet" type="text/css" />
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <title>Service & Support</title>
    </asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="cpSerSup" runat="server">
    <div class="divBody">
        <div class ="divSpacing"></div>
        <div class="divServiceContentContain">
            <div class="divHeader">
                <asp:Label ID="lblHeader" class="header" runat="server" />
            </div>

            <div style="padding:20px;"></div>

            <div class="divBtn marginClass">
                <div style ="width: 33%;"> <asp:Button ID="btnFAQ" class="btnSerSup" runat="server" OnClick="btnFAQ_Click" /> </div> &nbsp
                <div style ="width: 33%;"> <asp:Button ID="btnFeedback" class="btnSerSup" runat="server" OnClick="btnFeedback_Click" /> </div> &nbsp
                <div style ="width: 33%;"> <asp:Button ID="btnPassRecover" class="btnSerSup" runat="server" OnClick="btnPassRecover_Click" /> </div>
            </div>

             <div style="padding:20px;"></div>

            <asp:MultiView ID="mvSerSupSelect" runat="server">
                <asp:View ID="viewFAQ" runat="server">
                    <asp:MultiView ID="mvUserType" runat="server">
                        <asp:View ID="viewAdmin" runat="server">
                            <div class="btnRight marginClass">
                                <asp:Button ID="btnInsertFAQ"  CssClass="btnInsertFAQ dropShadow" runat="server" OnClick="btnInsertFAQ_Click" />
                            </div>
                    
                            <div style="padding:10px;"></div>
                            
                            <asp:GridView ID="GridViewFAQ" CssClass="GridViewFAQ" runat="server" AutoGenerateColumns="False" CellPadding="10" ForeColor="#333333" GridLines="None" 
                                AutoGenerateDeleteButton="True" 
                                AutoGenerateEditButton="True" DataKeyNames="questionID" DataSourceID="SqlDataSource1" BorderStyle="None" Font-Size="15pt" >

                                <AlternatingRowStyle BackColor="White"  />
                                <Columns>
                                    <asp:BoundField DataField="questionID" HeaderText="Question ID" InsertVisible="False" ReadOnly="True" SortExpression="questionID" />
                                    <asp:BoundField DataField="questionDesc" HeaderText="Question Description" SortExpression="questionDesc" />
                                    <asp:BoundField DataField="ansDesc" HeaderText="Answer Description" SortExpression="ansDesc" /> 
                                </Columns>

                                <EditRowStyle BackColor="#7Cbcb1" />
                                <FooterStyle BackColor="#b3eaee" Font-Bold="True" ForeColor="White" />
                                <HeaderStyle BackColor="#b3eaee" Font-Bold="True" ForeColor="White" HorizontalAlign="Center"/>
                                <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                                <RowStyle BackColor="white"  HorizontalAlign="Center"/>

                                <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                                <SortedAscendingCellStyle BackColor="#F8FAFA" />
                                <SortedAscendingHeaderStyle BackColor="#246B61" />
                                <SortedDescendingCellStyle BackColor="#D4DFE1" />
                                <SortedDescendingHeaderStyle BackColor="#15524A" />
                            </asp:GridView>

                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:databaseConstr %>" DeleteCommand="DELETE FROM [faqs] WHERE [questionID] = @questionID" InsertCommand="INSERT INTO [faqs] ([questionDesc], [ansDesc]) VALUES (@questionDesc, @ansDesc)" SelectCommand="SELECT * FROM [faqs]" UpdateCommand="UPDATE [faqs] SET [questionDesc] = @questionDesc, [ansDesc] = @ansDesc WHERE [questionID] = @questionID">
                                <DeleteParameters>
                                    <asp:Parameter Name="questionID" Type="Int32" />
                                </DeleteParameters>
                                <InsertParameters>
                                    <asp:Parameter Name="questionDesc" Type="String" />
                                    <asp:Parameter Name="ansDesc" Type="String" />
                                </InsertParameters>
                                <UpdateParameters>
                                    <asp:Parameter Name="questionDesc" Type="String" />
                                    <asp:Parameter Name="ansDesc" Type="String" />
                                    <asp:Parameter Name="questionID" Type="Int32" />
                                </UpdateParameters>
                            </asp:SqlDataSource>
                        </asp:View>

                        <asp:View ID="viewOther" runat="server">
                            <div class="marginClass">
                            <asp:ListView ID="ListView2" runat="server" DataSourceID="SqlDataSource3">
                                <EmptyDataTemplate>
                                    No data was returned.
                                </EmptyDataTemplate>
                                
                                <ItemSeparatorTemplate>
                                    <br />
                                    <br />
                                </ItemSeparatorTemplate>

                                <ItemTemplate>
                                    <li style="background-color: #e8feff;color: black; border-radius: 10px; font-family:'Poppins';" class="dropShadow">
                                        <div style="padding:20px; ">
                                            Question:
                                            <asp:Label ID="QuestionLabel" runat="server" Text='<%# Eval("Question") %>' />
                                            <br />

                                            Answer:
                                            <asp:Label ID="AnswerLabel" runat="server" Text='<%# Eval("Answer") %>' />
                                            <br />
                                        </div>
                                    </li>
                                </ItemTemplate>

                                <LayoutTemplate>
                                    <ul id="itemPlaceholderContainer" runat="server" style="font-family: Verdana, Arial, Helvetica, sans-serif;">
                                        <li runat="server" id="itemPlaceholder" />
                                    </ul>
                                    <div style="text-align: center;background-color: #FFCC66;font-family: Verdana, Arial, Helvetica, sans-serif;color: #333333;">
                                    </div>
                                </LayoutTemplate>
                            </asp:ListView>
                            <br />
                            </div>
                            <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:databaseConstr %>" SelectCommand="SELECT [questionDesc] as Question, [ansDesc] as Answer FROM [faqs]"></asp:SqlDataSource>
                        </asp:View>
                    </asp:MultiView>
                </asp:View>
                

                <asp:View ID="viewFeedback" runat="server">
                    <asp:MultiView ID="mvUserTypeFeed" runat="server">
                        <asp:View ID="viewFeedAdmin" runat="server">
                            <div class="btnRight marginClass">
                                <asp:Button ID="btnAddFeedQues" runat="server" CssClass="btnInsertFAQ dropShadow" Text="+ Add Question" OnClick="btnAddFeedQues_Click" />
                                    &nbsp;
                                <asp:Button ID="btnViewRes" style="width: 170px;" runat="server" CssClass="btnInsertFAQ dropShadow" Text="View Responses" OnClick="btnViewRes_Click" />      
                            </div>

                            <br />

                            <div class="marginClass">
                                <asp:GridView ID="GridView1" class="GridViewFAQ" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="feedbackFormQuesID" DataSourceID="SqlDataSource2" CellPadding="10" GridLines="None" Width="100%" Font-Size="15pt">
                                    <Columns>
                                        <asp:BoundField DataField="feedbackQuesDesc" HeaderText="Feedback Questions" SortExpression="feedbackQuesDesc" />
                                    </Columns>
                                    <EditRowStyle BackColor="#7CBCB1" Font-Size="Large" />
                                    <FooterStyle BackColor="#B3EAEE" />
                                    <HeaderStyle BackColor="#B3EAEE" ForeColor="White" HorizontalAlign="Center" />

                                    <RowStyle HorizontalAlign="Center" />

                                </asp:GridView>
                            </div>

                            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:databaseConstr %>" DeleteCommand="DELETE FROM [feedbackForm] WHERE [feedbackFormQuesID] = @feedbackFormQuesID" InsertCommand="INSERT INTO [feedbackForm] ([feedbackQuesDesc]) VALUES (@feedbackQuesDesc)" SelectCommand="SELECT [feedbackFormQuesID], [feedbackQuesDesc] FROM [feedbackForm]" UpdateCommand="UPDATE [feedbackForm] SET [feedbackQuesDesc] = @feedbackQuesDesc WHERE [feedbackFormQuesID] = @feedbackFormQuesID">
                                <DeleteParameters>
                                    <asp:Parameter Name="feedbackFormQuesID" Type="Int32" />
                                </DeleteParameters>
                                <InsertParameters>
                                    <asp:Parameter Name="feedbackQuesDesc" Type="String" />
                                </InsertParameters>
                                <UpdateParameters>
                                    <asp:Parameter Name="feedbackQuesDesc" Type="String" />
                                    <asp:Parameter Name="feedbackFormQuesID" Type="Int32" />
                                </UpdateParameters>
                            </asp:SqlDataSource>
                        </asp:View>

                        <asp:View ID="viewOtherFeed" runat="server">
                            <div class="marginClass">
                                <div style="padding:20px;"></div>

                                Any Feedback to our club ? ( Your feedback will be anonymous )

                                <div style="padding:10px;"></div>

                                <asp:TextBox ID="txtFeedBackUser" runat="server" Height="200px" Width="100%"></asp:TextBox>
                                
                                <div style="padding:20px;"></div>

                                <asp:Button ID="btnSubmitFeedBack" CssClass="btnInsertFAQ" runat="server" Text="Submit" OnClick="btnSubmitFeedBack_Click" />
                                <asp:Label style="color: cadetblue;" ID="lblFeedbackToFeedback" runat="server"></asp:Label>
                            </div>
                        </asp:View>
                    </asp:MultiView>
                </asp:View>
            </asp:MultiView>

            <div class ="divSpacing"></div>
        </div>

        <div class ="divSpacing"></div>
    </div>
    
</asp:Content>
